// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjm_n0XpoK-T-DPMk6bOAPW1VC8PO11o',
    appId: '1:303999152293:web:007e0bef892fad4cfa5d4c',
    messagingSenderId: '303999152293',
    projectId: 'blogapplicationgraphql',
    authDomain: 'blogapplicationgraphql.firebaseapp.com',
    storageBucket: 'blogapplicationgraphql.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5JccFGDvUl1BdtoVKieZqIz3H0BQ-KyU',
    appId: '1:303999152293:android:0745cf7faff60d91fa5d4c',
    messagingSenderId: '303999152293',
    projectId: 'blogapplicationgraphql',
    storageBucket: 'blogapplicationgraphql.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHphaAr3B3s33q2R9GcTrnmBMg4g3NnDg',
    appId: '1:303999152293:ios:20f92cd71e7d0c17fa5d4c',
    messagingSenderId: '303999152293',
    projectId: 'blogapplicationgraphql',
    storageBucket: 'blogapplicationgraphql.appspot.com',
    iosBundleId: 'com.example.blogApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHphaAr3B3s33q2R9GcTrnmBMg4g3NnDg',
    appId: '1:303999152293:ios:701e687cf40701e4fa5d4c',
    messagingSenderId: '303999152293',
    projectId: 'blogapplicationgraphql',
    storageBucket: 'blogapplicationgraphql.appspot.com',
    iosBundleId: 'com.example.blogApplication.RunnerTests',
  );
}
